name: 4D-humans
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - numpy=1.26.4
  - pytorch
  - pytorch-cuda=11.8
  - torchvision=0.18.0
  - pip
  - pip:
    - pytorch-lightning==2.2.4
    - smplx==0.1.28
    - pyrender==0.1.45
    - opencv-python==4.9.0.80
    - yacs==0.1.8
    - scikit-image==0.23.2
    - einops==0.8.0
    - timm==1.0.3
    - dill==0.3.8
    - pandas==2.2.2
    - git+https://github.com/facebookresearch/detectron2
    - git+https://github.com/mattloper/chumpy

    # For training
    - rich
    - hydra-core
    - hydra-submitit-launcher
    - hydra-colorlog
    - pyrootutils
    - webdataset
